apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: web.${WERCKER_GIT_BRANCH}
  labels:
    app: web
    suffix: ${WERCKER_GIT_BRANCH}
spec:
  replicas: 2
  selector:
    matchLabels:
      branch: ${WERCKER_GIT_BRANCH}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        branch: ${WERCKER_GIT_BRANCH}
    spec:
      containers:
        - name: web-lang-server
          image: asia.gcr.io/${GCP_PROJECT_NAME}/inspectorium:${WERCKER_GIT_COMMIT}
          ports:
            - containerPort: 4000
              protocol: TCP
              name: http
          imagePullPolicy: Always
