apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    # requirements: create static ip via:
    # $ gcloud compute addresses create ingress-ip --global
    kubernetes.io/ingress.global-static-ip-name: ingress-ip
spec:
  rules:
  - host: master.inspect.quramy.net
    http:
      paths:
        - backend:
            serviceName: web-master
            servicePort: 4000
