apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    # requirements: create static ip via:
    # $ gcloud compute addresses create ingress-ip --global
    kubernetes.io/ingress.global-static-ip-name: ingress-ip
spec:
  backend:
    serviceName: web
    servicePort: 4000
# rules:
#   #- host: inspectorium.quramy.net
# - http:
#     paths:
#     - path: /*
#       backend:
#         serviceName: web
#         servicePort: 4000
