apiVersion: v1
kind: Service
metadata:
  name: web-${WERCKER_GIT_BRANCH}
  labels:
    app: web
    name: web-${WERCKER_GIT_BRANCH}
    suffix: ${WERCKER_GIT_BRANCH}
spec:
  type: NodePort 
  selector:
    name: web
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP 

